// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8r4GJ7XEz-JuVvSAl7bpScsP85aDAxO8',
    appId: '1:831938772599:web:211e38e098c2fb5c5b9072',
    messagingSenderId: '831938772599',
    projectId: 'sraddha-5ad17',
    authDomain: 'sraddha-5ad17.firebaseapp.com',
    storageBucket: 'sraddha-5ad17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvqq5b04mhv1GRw3i5HFQmBNb4DfPmhzE',
    appId: '1:831938772599:android:0385bf88f6fc0b295b9072',
    messagingSenderId: '831938772599',
    projectId: 'sraddha-5ad17',
    storageBucket: 'sraddha-5ad17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGYhMLt3QMqDFmHLxBpgmlsXKW9u4blU',
    appId: '1:831938772599:ios:526efc8821bccb0f5b9072',
    messagingSenderId: '831938772599',
    projectId: 'sraddha-5ad17',
    storageBucket: 'sraddha-5ad17.firebasestorage.app',
    iosBundleId: 'com.example.sraddha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGYhMLt3QMqDFmHLxBpgmlsXKW9u4blU',
    appId: '1:831938772599:ios:526efc8821bccb0f5b9072',
    messagingSenderId: '831938772599',
    projectId: 'sraddha-5ad17',
    storageBucket: 'sraddha-5ad17.firebasestorage.app',
    iosBundleId: 'com.example.sraddha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8r4GJ7XEz-JuVvSAl7bpScsP85aDAxO8',
    appId: '1:831938772599:web:2931b1f08e2151145b9072',
    messagingSenderId: '831938772599',
    projectId: 'sraddha-5ad17',
    authDomain: 'sraddha-5ad17.firebaseapp.com',
    storageBucket: 'sraddha-5ad17.firebasestorage.app',
  );
}
